### ISSUE TITLE
Hue Temperature Crashes on Startup

### ISSUE THREAD

**Issue by bam2000** [marcjordant/homebridge-hue-temperature#4]
hi,
i have installed your nice home bridge plugin, but I can't get it to work, because when I try to start homebridge it crashes with the following error message:

```
/usr/lib/node_modules/homebridge-hue-temperature/index.js:50
              var temperatureObj = statusObj["state"]["temperature"].toString();
                                                                    ^

TypeError: Cannot read property 'toString' of undefined
    at /usr/lib/node_modules/homebridge-hue-temperature/index.js:50:69
    at Request._callback (/usr/lib/node_modules/homebridge-hue-temperature/index.js:155:17)
    at Request.self.callback (/usr/lib/node_modules/homebridge-hue-temperature/node_modules/request/request.js:188:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (/usr/lib/node_modules/homebridge-hue-temperature/node_modules/request/request.js:1171:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (/usr/lib/node_modules/homebridge-hue-temperature/node_modules/request/request.js:1091:12)
    at IncomingMessage.g (events.js:292:16)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
```

Is there a problem on the plugin or with my config?

Thanks for your help :)

**Comment by marcjordant** [comment]
Can you show your config ?

**Comment by bam2000** [comment]
this is the Hue temperature part of my config:
`{
  "accessory": "HueTemperature",
  "name": "Temperatur Flur",
  "hue-bridge-ip-address": "192.168.1.253",
  "hue-bridge-username": "WG0aGAAa7u3J7MAb2Xv4iZ9MnHNVDlXGRA0v4xeW",
  "hue-sensor-id": "1"
}`

**Comment by marcjordant** [comment]
Can you show me what you get when you run the following command in terminal:

`curl -s -X GET http://192.168.1.253/api/WG0aGAAa7u3J7MAb2Xv4iZ9MnHNVDlXGRA0v4xeW/sensors/1
`

**Comment by bam2000** [comment]
`{"state":{"daylight":null,"lastupdated":"none"},"config":{"on":true,"configured":false,"sunriseoffset":30,"sunsetoffset":-30},"name":"Daylight","type":"Daylight","modelid":"PHDL00","manufacturername":"Philips","swversion":"1.0"}`

I can't see any information about the current temperature of the sensor, do you think I have choose the wrong ? but I just have 4 items, two sensors and two hue dimmer... my motion sensors are 1 and 4. and I can see the temperature with iconnecthue app on my smartphone :/

**Comment by marcjordant** [comment]
It seems this is not the correct sensor (id : 1)
The modelId should be "SML001" or something like that. Also you should have a type property with the value "ZLLTemperature".

Please use the correct sensor id.

**Comment by bam2000** [comment]
Thanks for the hint :)
Fixed it and it is working fine 👍

**Comment by marcjordant** [comment]
👍
